### ISSUE TITLE
feat: 相关的图片资源未上传

### ISSUE THREAD

**Issue by SaucePlum** [cat991/py-go-cqhttp#1]
补一下???

**Comment by cat991** [comment]
[warframe.strategy.rar](https://github.com/cat991/py-go-cqhttp/releases/download/preview/warframe.strategy.rar)
你说的是战甲攻略的资源吗

**Comment by SaucePlum** [comment]
![image](https://user-images.githubusercontent.com/48905684/174208771-406a15fc-cb2d-4ef9-aba8-46a949039312.png)

**Comment by SaucePlum** [comment]
拔萝卜这个

**Comment by cat991** [comment]
> ![image](https://user-images.githubusercontent.com/48905684/174208771-406a15fc-cb2d-4ef9-aba8-46a949039312.png)

这个是自动生成的，如果报错的话你可以尝试新建这个文件夹给他

**Comment by SaucePlum** [comment]
![image](https://user-images.githubusercontent.com/48905684/174211055-671db932-8986-4521-bd71-de0047be49a4.png)
拔萝卜这个的yml配置文件没commit  以及涉及的一些资源文件也不完整

**Comment by cat991** [comment]
> ![image](https://user-images.githubusercontent.com/48905684/174211055-671db932-8986-4521-bd71-de0047be49a4.png) 拔萝卜这个的yml配置文件没commit 以及涉及的一些资源文件也不完整
[Releases](https://github.com/cat991/py-go-cqhttp/releases)
这里上传的只是程序源码和需要的框架，资源文件的话都统一打包到releases里了

**Comment by SaucePlum** [comment]
好的👌



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 17, 2022 10:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cat991/py-go-cqhttp] feat: 相关的图片资源未上传 (Issue #1)




  
 拔萝卜这个的yml配置文件没commit 以及涉及的一些资源文件也不完整
 Releases
 这里上传的只是程序源码和需要的框架，资源文件的话都统一打包到releases里了
